"""add_project_members_for_sharing

Revision ID: 9022b5971b70
Revises: f7a8b9c0d1e2
Create Date: 2025-12-24 08:43:20.625284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9022b5971b70'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use existing user_role enum instead of creating it
    user_role_enum = postgresql.ENUM('ADMIN', 'SUBSCRIBER', 'ANALYST', 'VIEWER', name='user_role', create_type=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Supabase Auth user UUID'),
    sa.Column('access_level', user_role_enum, nullable=False, comment='Role of this user for this specific project'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index('ix_project_members_project_user', 'project_members', ['project_id', 'user_id'], unique=True)
    op.create_index('ix_project_members_user', 'project_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.UUID(),
               comment='Supabase Auth user UUID of project owner',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Supabase Auth user UUID of project owner',
               existing_nullable=False)
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index('ix_project_members_user', table_name='project_members')
    op.drop_index('ix_project_members_project_user', table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    # ### end Alembic commands ###
