"""Add AI conversation history table

Revision ID: 302c7583b1c8
Revises: fc75a7b4d179
Create Date: 2026-01-06 13:05:57.513075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302c7583b1c8'
down_revision: Union[str, None] = 'fc75a7b4d179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('comparison_name', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Supabase Auth user UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_comparison_name'), 'ai_conversations', ['comparison_name'], unique=False)
    op.create_index('ix_ai_conversations_dataset_comparison', 'ai_conversations', ['dataset_id', 'comparison_name'], unique=False)
    op.create_index(op.f('ix_ai_conversations_dataset_id'), 'ai_conversations', ['dataset_id'], unique=False)
    op.create_index('ix_ai_conversations_user', 'ai_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_user', table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_dataset_id'), table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_dataset_comparison', table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_comparison_name'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
