"""Add user subscription and AI quota management

Revision ID: 6783e8d60345
Revises: 4e53023ccf57
Create Date: 2026-01-06 17:15:58.026229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6783e8d60345'
down_revision: Union[str, None] = '4e53023ccf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Supabase Auth user UUID'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role_enum'), nullable=False),
    sa.Column('subscription_plan', sa.Enum('BASIC', 'PREMIUM', 'ADVANCED', name='subscription_plan_enum'), nullable=False),
    sa.Column('ai_interpretations_used', sa.Integer(), nullable=False),
    sa.Column('ai_tokens_purchased', sa.Integer(), nullable=False),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=False),
    sa.Column('subscription_starts_at', sa.String(length=50), nullable=True),
    sa.Column('subscription_ends_at', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='interpretation or question'),
    sa.Column('comparison_name', sa.String(length=255), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('was_free', sa.Boolean(), nullable=False, comment='True if within free quota, False if purchased token'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_usage_logs_user_created', 'ai_usage_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    
    # Migrate access_level enum type safely
    # Step 1: Add new column with new enum type
    op.add_column('project_members', sa.Column('access_level_new', sa.Enum('ADMIN', 'USER', name='user_role_enum'), nullable=True))
    
    # Step 2: Map old values to new values (SUBSCRIBER, ANALYST, VIEWER -> USER)
    op.execute("UPDATE project_members SET access_level_new = CASE WHEN access_level::text = 'ADMIN' THEN 'ADMIN'::user_role_enum ELSE 'USER'::user_role_enum END")
    
    # Step 3: Drop old column and rename new column
    op.drop_column('project_members', 'access_level')
    op.alter_column('project_members', 'access_level_new', new_column_name='access_level', nullable=False)
    
    # Step 4: Drop old enum type
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate old enum type
    sa.Enum('ADMIN', 'SUBSCRIBER', 'ANALYST', 'VIEWER', name='user_role').create(op.get_bind(), checkfirst=True)
    
    # Revert access_level column
    op.add_column('project_members', sa.Column('access_level_old', postgresql.ENUM('ADMIN', 'SUBSCRIBER', 'ANALYST', 'VIEWER', name='user_role'), nullable=True))
    op.execute("UPDATE project_members SET access_level_old = 'SUBSCRIBER'::user_role")
    op.drop_column('project_members', 'access_level')
    op.alter_column('project_members', 'access_level_old', new_column_name='access_level', nullable=False)
    
    # Drop new enum
    sa.Enum(name='user_role_enum').drop(op.get_bind(), checkfirst=True)
    
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_user_created', table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
