"""Add DegGene and EnrichmentPathway models

Revision ID: fc75a7b4d179
Revises: 9022b5971b70
Create Date: 2026-01-03 13:18:12.745858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc75a7b4d179'
down_revision: Union[str, None] = '9022b5971b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False, comment='Gene set name (e.g., GO:0006955, HALLMARK_TNFA_SIGNALING_VIA_NFKB)'),
    sa.Column('database', sa.Enum('GO_BP', 'GO_MF', 'GO_CC', 'KEGG', 'REACTOME', 'HALLMARK', 'C2_CURATED', 'C5_ONTOLOGY', 'C6_ONCOGENIC', 'C7_IMMUNOLOGIC', 'CUSTOM', name='gene_set_database'), nullable=False, comment='Source database'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description of the gene set'),
    sa.Column('genes', sa.JSON(), nullable=False, comment='List of gene symbols in this gene set'),
    sa.Column('size', sa.Integer(), nullable=False, comment='Number of genes in the set'),
    sa.Column('gene_set_metadata', sa.JSON(), nullable=False, comment='Additional metadata (GO term hierarchy, pathway URL, etc.)'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='Version of the gene set database (e.g., GO 2024-01, MSigDB 2024.1)'),
    sa.Column('organism', sa.String(length=100), nullable=False, comment='Organism for this gene set'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gene_sets_database'), 'gene_sets', ['database'], unique=False)
    op.create_index('ix_gene_sets_database_organism', 'gene_sets', ['database', 'organism'], unique=False)
    op.create_index(op.f('ix_gene_sets_name'), 'gene_sets', ['name'], unique=False)
    op.create_index('ix_gene_sets_name_database', 'gene_sets', ['name', 'database'], unique=True)
    op.create_index(op.f('ix_gene_sets_organism'), 'gene_sets', ['organism'], unique=False)
    op.create_index('ix_gene_sets_size', 'gene_sets', ['size'], unique=False)
    op.create_table('deg_genes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('comparison_name', sa.String(length=255), nullable=False),
    sa.Column('gene_id', sa.String(length=255), nullable=False),
    sa.Column('gene_name', sa.String(length=255), nullable=True),
    sa.Column('base_mean', sa.Float(), nullable=True),
    sa.Column('log_fc', sa.Float(), nullable=True),
    sa.Column('pvalue', sa.Float(), nullable=True),
    sa.Column('padj', sa.Float(), nullable=True),
    sa.Column('regulation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deg_genes_comparison_name'), 'deg_genes', ['comparison_name'], unique=False)
    op.create_index('ix_deg_genes_dataset_comparison', 'deg_genes', ['dataset_id', 'comparison_name'], unique=False)
    op.create_index('ix_deg_genes_dataset_comparison_regulation', 'deg_genes', ['dataset_id', 'comparison_name', 'regulation'], unique=False)
    op.create_index(op.f('ix_deg_genes_dataset_id'), 'deg_genes', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_deg_genes_gene_id'), 'deg_genes', ['gene_id'], unique=False)
    op.create_index(op.f('ix_deg_genes_log_fc'), 'deg_genes', ['log_fc'], unique=False)
    op.create_index(op.f('ix_deg_genes_padj'), 'deg_genes', ['padj'], unique=False)
    op.create_index(op.f('ix_deg_genes_regulation'), 'deg_genes', ['regulation'], unique=False)
    op.create_table('enrichment_pathways',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('comparison_name', sa.String(length=255), nullable=False),
    sa.Column('pathway_id', sa.String(length=255), nullable=False),
    sa.Column('pathway_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gene_count', sa.Integer(), nullable=False),
    sa.Column('pvalue', sa.Float(), nullable=False),
    sa.Column('padj', sa.Float(), nullable=False),
    sa.Column('gene_ratio', sa.String(length=50), nullable=True),
    sa.Column('bg_ratio', sa.String(length=50), nullable=True),
    sa.Column('genes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_pathways_category'), 'enrichment_pathways', ['category'], unique=False)
    op.create_index(op.f('ix_enrichment_pathways_comparison_name'), 'enrichment_pathways', ['comparison_name'], unique=False)
    op.create_index('ix_enrichment_pathways_dataset_comparison', 'enrichment_pathways', ['dataset_id', 'comparison_name'], unique=False)
    op.create_index(op.f('ix_enrichment_pathways_dataset_id'), 'enrichment_pathways', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_enrichment_pathways_padj'), 'enrichment_pathways', ['padj'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_pathways_padj'), table_name='enrichment_pathways')
    op.drop_index(op.f('ix_enrichment_pathways_dataset_id'), table_name='enrichment_pathways')
    op.drop_index('ix_enrichment_pathways_dataset_comparison', table_name='enrichment_pathways')
    op.drop_index(op.f('ix_enrichment_pathways_comparison_name'), table_name='enrichment_pathways')
    op.drop_index(op.f('ix_enrichment_pathways_category'), table_name='enrichment_pathways')
    op.drop_table('enrichment_pathways')
    op.drop_index(op.f('ix_deg_genes_regulation'), table_name='deg_genes')
    op.drop_index(op.f('ix_deg_genes_padj'), table_name='deg_genes')
    op.drop_index(op.f('ix_deg_genes_log_fc'), table_name='deg_genes')
    op.drop_index(op.f('ix_deg_genes_gene_id'), table_name='deg_genes')
    op.drop_index(op.f('ix_deg_genes_dataset_id'), table_name='deg_genes')
    op.drop_index('ix_deg_genes_dataset_comparison_regulation', table_name='deg_genes')
    op.drop_index('ix_deg_genes_dataset_comparison', table_name='deg_genes')
    op.drop_index(op.f('ix_deg_genes_comparison_name'), table_name='deg_genes')
    op.drop_table('deg_genes')
    op.drop_index('ix_gene_sets_size', table_name='gene_sets')
    op.drop_index(op.f('ix_gene_sets_organism'), table_name='gene_sets')
    op.drop_index('ix_gene_sets_name_database', table_name='gene_sets')
    op.drop_index(op.f('ix_gene_sets_name'), table_name='gene_sets')
    op.drop_index('ix_gene_sets_database_organism', table_name='gene_sets')
    op.drop_index(op.f('ix_gene_sets_database'), table_name='gene_sets')
    op.drop_table('gene_sets')
    # ### end Alembic commands ###
