"""Add AI interpretation table

Revision ID: 4e53023ccf57
Revises: 302c7583b1c8
Create Date: 2026-01-06 14:24:28.523445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e53023ccf57'
down_revision: Union[str, None] = '302c7583b1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interpretations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('comparison_name', sa.String(length=255), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('deg_up', sa.Integer(), nullable=False),
    sa.Column('deg_down', sa.Integer(), nullable=False),
    sa.Column('pathways_count', sa.Integer(), nullable=False),
    sa.Column('genes_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interpretations_comparison_name'), 'ai_interpretations', ['comparison_name'], unique=False)
    op.create_index('ix_ai_interpretations_dataset_comparison', 'ai_interpretations', ['dataset_id', 'comparison_name'], unique=True)
    op.create_index(op.f('ix_ai_interpretations_dataset_id'), 'ai_interpretations', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_interpretations_dataset_id'), table_name='ai_interpretations')
    op.drop_index('ix_ai_interpretations_dataset_comparison', table_name='ai_interpretations')
    op.drop_index(op.f('ix_ai_interpretations_comparison_name'), table_name='ai_interpretations')
    op.drop_table('ai_interpretations')
    # ### end Alembic commands ###
