#!/usr/bin/env Rscript
# ==============================================================================
# list_anno_db_categories.R
# Utility script — introspect anno.db RDS files and output a JSON catalogue.
#
# Usage:
#   Rscript list_anno_db_categories.R <anno_db_dir> <output_json>
#
# Example:
#   Rscript backend/r_scripts/list_anno_db_categories.R \
#       pipe_scilicium/resources/anno.db \
#       backend/app/data/anno_db_categories.json
#
# Output format:
#   {
#     "human": ["GO_BP", "GO_MF", ...],
#     "mouse": [...],
#     ...
#   }
# ==============================================================================

suppressPackageStartupMessages({
  library(jsonlite)
})

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2) {
  stop("Usage: list_anno_db_categories.R <anno_db_dir> <output_json>")
}

anno_db_dir <- args[1]
output_json <- args[2]

if (!dir.exists(anno_db_dir)) {
  stop("Anno DB directory not found: ", anno_db_dir)
}

# Find all anno.db RDS files
rds_files <- list.files(anno_db_dir, pattern = "^anno\\.db\\..*\\.rds$", full.names = TRUE)

if (length(rds_files) == 0) {
  stop("No anno.db RDS files found in: ", anno_db_dir)
}

message("Found ", length(rds_files), " anno.db files")

# Excluded categories (low-level / not biologically meaningful for enrichment)
EXCLUDE_PATTERN <- "^NCBI_|^chromosome_location$|^xrefs$|^interactions$|^regulations$"

result <- list()

for (rds_file in sort(rds_files)) {
  filename <- basename(rds_file)
  # Extract species from filename: anno.db.<species>.gene_symbol.<date>.rds
  species_match <- regmatches(filename, regexpr("anno\\.db\\.([^.]+)\\.gene_symbol", filename))
  if (length(species_match) == 0) {
    message("  Skipping (cannot parse species from filename): ", filename)
    next
  }
  species_name <- sub("anno\\.db\\.([^.]+)\\.gene_symbol", "\\1", species_match)
  message("  Processing: ", filename, " → species: ", species_name)

  tryCatch({
    anno.db.obj <- readRDS(rds_file)
    if (!is.list(anno.db.obj) || is.null(anno.db.obj$annotations)) {
      message("    WARNING: unexpected structure, skipping")
      next
    }
    categories <- names(anno.db.obj$annotations)

    # Filter excluded categories
    exclude_idx <- grep(EXCLUDE_PATTERN, categories)
    if (length(exclude_idx) > 0) {
      categories <- categories[-exclude_idx]
    }

    # Keep only non-empty matrices
    categories <- Filter(function(cat) {
      m <- anno.db.obj$annotations[[cat]]
      ncol(m) > 0
    }, categories)

    message("    Found ", length(categories), " usable categories")
    result[[species_name]] <- sort(categories)

  }, error = function(e) {
    message("    ERROR loading ", filename, ": ", e$message)
  })
}

# Write JSON output
output_data <- c(
  list(`_comment` = "Generated by list_anno_db_categories.R. Re-run after anno.db updates."),
  result
)

dir.create(dirname(output_json), showWarnings = FALSE, recursive = TRUE)
write(toJSON(output_data, pretty = TRUE, auto_unbox = TRUE), output_json)

message("\n=== Written to: ", output_json, " ===")
message("Species catalogued: ", paste(names(result), collapse = ", "))
